PAYLOAD_ACTIVATION_TIME = [500, 30] select scv_debug;
publicVariable "PAYLOAD_ACTIVATION_TIME";
PAYLOAD_MAXIMUM_COUNT = 10;
publicVariable "PAYLOAD_MAXIMUM_COUNT";
RESPAWN_TICKETS_COUNT = 20;
publicVariable "RESPAWN_TICKETS_COUNT";